name: Deploy Docker Container to Azure VM

on:
  push:
    branches:
      - release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/autofeedback-testing-tool:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/autofeedback-testing-tool:latest

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.AZURE_VM_IP }} >> ~/.ssh/known_hosts

    - name: Deploy Docker container on Azure VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/autofeedback-testing-tool:latest
          docker stop autofeedback-testing-tool || true
          docker rm autofeedback-testing-tool || true
          docker run \
            -d --name autofeedback-testing-tool \
            -e API_KEY_CHAT_GPT=sk-svcacct-Fs4LudxZOMDPevQnqlNdOUwWpxZo3qkHwk3M55BAHQvFhhx0O5ZitnXVxikKKqSe2km8T3BlbkFJY0tVxKSXbbcqiL1UfOgsyovCAi2K1xf-98hqeoQkjPrl51_BCNIWK3UHeIrKYXh3ZYIA \
            -e ANTHROPIC_API_KEY=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 \
            -e API_KEY_LLAMA=LA-73bb5ae0fd3d4ff581a4f52b93ecf422ef697d176ed44b4b813411af96786c3c \
            -e API_KEY_GEMINI=AIzaSyCERyVxnZJca0ywCiy5e8Nio1NcKGaTlNM \
            -e DB_URL=mongodb://0.0.0.0:27017/autofeedback-test-tool \
            -e REACT_APP_API=http://localhost:8000/api \
            --network autofeedback-testing-tool \
            -p 80:8000 ${{ secrets.DOCKER_USERNAME }}/autofeedback-testing-tool:latest
        EOF
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
